# Generated by Django 4.0 on 2021-12-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('iron_content', models.PositiveSmallIntegerField(default=0, help_text='Поставьте оценку', verbose_name='Содержание железа')),
                ('sera_content', models.PositiveSmallIntegerField(default=0, help_text='Поставьте оценку', verbose_name='Содержание серы')),
                ('other_content', models.PositiveSmallIntegerField(default=0, help_text='Поставьте оценку', verbose_name='Иные содержания')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rest.month', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
            },
        ),
    ]
